=== powcoder/fit3176-database/solns-topic08/pubs/pub1.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- 
    Pub1 schema file
    Task 2 (i)
    
    Author: Sample Solutions
    
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="publications">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="book" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="title" type="xs:string"/>
                        <xs:element name="author" type="xs:string"/>
                        <xs:element name="datepublished" type="xs:date"/>
                        <xs:element name="nopages" type="xs:positiveInteger"/>
                        <xs:element name="price" type="xs:decimal"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        
    </xs:complexType>
    
</xs:element>

</xs:schema>

=== powcoder/fit3176-database/solns-topic08/pubs/pub1.xml
<?xml version="1.0" encoding="UTF-8" ?>

<!--
    Publications data
    Author: Sample Solutions
    
    pub1.xml
-->


<publications xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="pub1.xsd">
    <book>
        <title>XML in a Nutshell, Third Edition</title>
        <author>Elliotte Rusty Harodls; W. Scott Means</author>
        <datepublished>2004-09-01</datepublished>
        <nopages>600</nopages>
        <price>89.95</price>
    </book>
    <book>
        <title>XML Schemas</title>
        <author>Chelsea Valentine; Lucinda Dykes; Ed Tittel</author>
        <datepublished>2001-10-26</datepublished>
        <nopages>500</nopages>
        <price>82.56</price>
    </book>
    <book>
        <title>New Perspectives on XML 2nd Edition Comprehensive</title>
        <author>Patrick Carey</author>
        <datepublished>2006-08-17</datepublished>
        <nopages>736</nopages>
        <price>102.00</price>
    </book>

</publications>
